
# Cuadernillo de Vectores y Matrices con Numpy

Este cuadernillo tiene como objetivo proporcionar una introducción práctica a la definición de vectores y matrices, operaciones básicas entre ellos, y cálculo de la magnitud de un vector usando la biblioteca Numpy.
    

In [1]:
# Importar la biblioteca Numpy
import numpy as np


## Definición de Vector y Matriz
    

In [9]:

# Definición de un vector
vector = np.array([1, 2, 3])
print("Vector:", vector)

# Definición de una matriz
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Matriz:\n", matriz)
    

Vector: [1 2 3]
Matriz:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



## Operaciones Básicas entre Vectores y Matrices
    

In [10]:
# Suma de vectores
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
suma_vectores = np.subtract(vector1, vector2)
print("Suma de vectores:", suma_vectores)    

Suma de vectores: [-3 -3 -3]


In [5]:
# Producto escalar entre vectores
producto_escalar = np.dot(vector1, vector2)
print("Producto escalar:", producto_escalar)

Producto escalar: 32


In [6]:
# Multiplicación de matrices
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[2, 0], [1, 2]])
producto_matrices = np.dot(matriz1, matriz2)
print("Producto de matrices:\n", producto_matrices)

Producto de matrices:
 [[ 4  4]
 [10  8]]



## Cálculo de la Magnitud de un Vector
    

In [7]:
# Magnitud de un vector
magnitud_vector = np.linalg.norm(vector1)
print("Magnitud del vector:", magnitud_vector)    

Magnitud del vector: 3.7416573867739413


# Funciones para creación de matrices

In [21]:
a = np.zeros((2,2))  # Create an array of all zeros
b = np.ones((5,5)) # Create an array of all ones
c = np.full((5,5), 7) # Create a constant array
d = np.eye(5)        # Create a 2x2 identity matrix
e = np.random.random((5,5)) # Create an array filled with random values

In [23]:
matriz2 @ matriz1

array([[ 2,  4],
       [ 7, 10]])